/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BarberService } from "../barber.service";
import { BarberCreateInput } from "./BarberCreateInput";
import { Barber } from "./Barber";
import { BarberFindManyArgs } from "./BarberFindManyArgs";
import { BarberWhereUniqueInput } from "./BarberWhereUniqueInput";
import { BarberUpdateInput } from "./BarberUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";
import { BarberLocationInputDto } from "../BarberLocationInputDto";
import { BarberOutputDto } from "../BarberOutputDto";

export class BarberControllerBase {
  constructor(protected readonly service: BarberService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Barber })
  async createBarber(@common.Body() data: BarberCreateInput): Promise<Barber> {
    return await this.service.createBarber({
      data: data,
      select: {
        availability: true,
        createdAt: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        name: true,
        ratings: true,
        services: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Barber] })
  @ApiNestedQuery(BarberFindManyArgs)
  async barbers(@common.Req() request: Request): Promise<Barber[]> {
    const args = plainToClass(BarberFindManyArgs, request.query);
    return this.service.barbers({
      ...args,
      select: {
        availability: true,
        createdAt: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        name: true,
        ratings: true,
        services: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Barber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async barber(
    @common.Param() params: BarberWhereUniqueInput
  ): Promise<Barber | null> {
    const result = await this.service.barber({
      where: params,
      select: {
        availability: true,
        createdAt: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        name: true,
        ratings: true,
        services: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Barber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBarber(
    @common.Param() params: BarberWhereUniqueInput,
    @common.Body() data: BarberUpdateInput
  ): Promise<Barber | null> {
    try {
      return await this.service.updateBarber({
        where: params,
        data: data,
        select: {
          availability: true,
          createdAt: true,
          id: true,
          latitude: true,
          location: true,
          longitude: true,
          name: true,
          ratings: true,
          services: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Barber })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBarber(
    @common.Param() params: BarberWhereUniqueInput
  ): Promise<Barber | null> {
    try {
      return await this.service.deleteBarber({
        where: params,
        select: {
          availability: true,
          createdAt: true,
          id: true,
          latitude: true,
          location: true,
          longitude: true,
          name: true,
          ratings: true,
          services: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: BarberWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        barber: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        id: true,

        service: {
          select: {
            id: true,
          },
        },

        status: true,
        time: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: BarberWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateBarber({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: BarberWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateBarber({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: BarberWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateBarber({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/search-barbers")
  @swagger.ApiOkResponse({
    type: BarberOutputDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async SearchBarbers(
    @common.Body()
    body: BarberLocationInputDto
  ): Promise<BarberOutputDto[]> {
    return this.service.SearchBarbers(body);
  }
}
